const express = require('express');
const router = express.Router();
const User = require('../models/User');
const Team = require('../models/Team');
const Startup = require('../models/Startup');
const auth = require('../middleware/auth');
const adminOnly = (req, res, next) => { if (!req.user.isAdmin) return res.status(403).json({ success: false, message: 'Admin only' }); next(); };
router.use(auth, adminOnly);
router.get('/stats', async (req, res) => { try { const [users, teams, startups] = await Promise.all([User.countDocuments(), Team.countDocuments(), Startup.countDocuments()]); const activeUsers = await User.countDocuments({ lastActive: { $gte: new Date(Date.now() - 7*24*60*60*1000) } }); res.json({ success: true, stats: { users, teams, startups, activeUsers } }); } catch (err) { res.status(500).json({ success: false, message: err.message }); } });
router.get('/users', async (req, res) => { try { const { page = 1, limit = 20, search } = req.query; const filter = {}; if (search) filter.$or = [{ name: new RegExp(search, 'i') }, { email: new RegExp(search, 'i') }]; const users = await User.find(filter).select('-password').sort({ createdAt: -1 }).skip((page-1)*limit).limit(Number(limit)); const total = await User.countDocuments(filter); res.json({ success: true, users, total }); } catch (err) { res.status(500).json({ success: false, message: err.message }); } });
router.put('/users/:id/ban', async (req, res) => { try { const user = await User.findByIdAndUpdate(req.params.id, { isBanned: true }, { new: true }).select('-password'); res.json({ success: true, user }); } catch (err) { res.status(500).json({ success: false, message: err.message }); } });
router.put('/users/:id/unban', async (req, res) => { try { const user = await User.findByIdAndUpdate(req.params.id, { isBanned: false }, { new: true }).select('-password'); res.json({ success: true, user }); } catch (err) { res.status(500).json({ success: false, message: err.message }); } });
router.delete('/users/:id', async (req, res) => { try { await User.findByIdAndDelete(req.params.id); res.json({ success: true, message: 'User deleted' }); } catch (err) { res.status(500).json({ success: false, message: err.message }); } });
module.exports = router;
